import torch
import torch.nn as nn
import os
import random
from tqdm import tqdm
from datasets import load_dataset
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer, get_linear_schedule_with_warmup
from accelerate import Accelerator
import bitsandbytes as bnb 

# =======================================================
# 1. Environment Setup & Hyperparameters
# =======================================================
MODEL_DIR = snapshot_download('qwen/Qwen3-4B-Instruct-2507', cache_dir='./model_weights')
DATA_FILE = "path/to/data.json"
OUTPUT_DIR = "./qwen_4b_sft_output"
CITE_TOKEN = "[#CITE#]"
MAX_LEN = 1024
BATCH_SIZE = 2       
GRAD_ACCUM = 16      
LEARNING_RATE = 2e-5  

# Initialize Accelerator
accelerator = Accelerator(gradient_accumulation_steps=GRAD_ACCUM)
device = accelerator.device

tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR, trust_remote_code=True)

# Ensure the special token is added to the vocabulary
if CITE_TOKEN not in tokenizer.all_special_tokens:
    tokenizer.add_special_tokens({'additional_special_tokens': [CITE_TOKEN]})

# Self-check: Verify if [#CITE#] is correctly recognized as a single token ID
test_ids = tokenizer.encode(CITE_TOKEN, add_special_tokens=False)
if accelerator.is_main_process:
    print(f"[*] Tokenizer Check: '{CITE_TOKEN}' -> IDs: {test_ids}")
    if len(test_ids) > 1:
        print("[!] Warning: CITE_TOKEN was split into multiple IDs. Please check the tokenizer configuration!")

# =======================================================
# 2. Data Processing Logic
# =======================================================
raw_dataset = load_dataset("json", data_files=DATA_FILE, split="train")
dataset_dict = raw_dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = dataset_dict["train"]
test_dataset = dataset_dict["test"]

if accelerator.is_main_process:
    test_set_path = "test_CiteLocator.json"
    test_dataset.to_json(test_set_path, force_ascii=False)
    print(f"[*] Original test set saved ({len(test_dataset)} records in total)")

PROMPT_POOL = [
    "Identify non-trivial technical assertions and empirical claims within the provided text that lack explicit grounding. Insert the {token} marker at the precise syntactic boundary following each statement to denote where a supporting reference is epistemically mandatory for academic validation.",
    "Examine the manuscript for segments referencing specialized methodologies, prior research findings, or exogenous data points. You must locate the semantic transition where the author's narrative relies on external evidence and signify this by appending the {token} identifier at the end of the corresponding clause.",
    "Perform a granular analysis of the logical flow to distinguish between original interpretations and claims that necessitate evidentiary support from the literature. For every instance where a sentence introduces a fact, benchmark, or theory not generated by the current study, place the {token} symbol at the exact junction where a citation is required.",
    "Scan the provided passage for technical definitions, conceptual frameworks, or algorithmic descriptions that are not common knowledge. Mark the terminal point of each identified assertion with the {token} placeholder to indicate that a formal bibliographic attribution must be integrated to maintain scholarly rigor.",
    "Detect specific assertions regarding state-of-the-art (SOTA) performance, historical research contexts, or comparative benchmarks. You are required to signify the need for external validation by embedding the {token} marker at the logical conclusion of each claim, ensuring it is positioned before any subsequent narrative transition.",
    "Analyze the discourse for 'semantic breakpoints'—locations where the argument relies on established scientific protocols or standardized procedures developed by others. Append the {token} identifier to these specific points to highlight the requirement for a formal reference to the original source.",
    "Systematically audit the text for technical claims that require comparative grounding in existing literature. Identify the precise syntactic location following each assertion and insert the {token} marker to act as a directive for necessary bibliographic inclusion without altering the original prose.",
    "Evaluate the text for assertions that introduce exogenous evidence or build upon the collective knowledge of the research community. For every claim that lacks explicit substantiation, determine the exact position where a citation is required and denote this by inserting the {token} identifier at that syntactic boundary."
]

def tokenize_fn(example):
    # Randomly select a prompt template for training diversity
    prompt = random.choice(PROMPT_POOL).format(token=CITE_TOKEN)
    
    # Construct prompt sequence: System + User + Assistant structuring
    prefix = f"<|im_start|>system\n{prompt}<|im_end|>\n<|im_start|>user\n{example['input']}<|im_end|>\n<|im_start|>assistant\n"
    target = f"{example['output']}<|im_end|>"
    
    # Tokenize prefix and target independently
    prefix_ids = tokenizer.encode(prefix, add_special_tokens=False)
    target_ids = tokenizer.encode(target, add_special_tokens=False)
    
    # Concatenate and apply label masking 
    # (The model only computes loss on target_ids; prefix_ids are masked with -100)
    input_ids = prefix_ids + target_ids
    labels = [-100] * len(prefix_ids) + target_ids
    
    # Apply truncation
    if len(input_ids) > MAX_LEN:
        input_ids = input_ids[:MAX_LEN]
        labels = labels[:MAX_LEN]
        
    # Apply padding
    padding_len = MAX_LEN - len(input_ids)
    input_ids += [tokenizer.pad_token_id] * padding_len
    labels += [-100] * padding_len
    attention_mask = [1] * (MAX_LEN - padding_len) + [0] * padding_len
    
    return {
        "input_ids": torch.tensor(input_ids), 
        "attention_mask": torch.tensor(attention_mask), 
        "labels": torch.tensor(labels)
    }

tokenized_train = train_dataset.map(tokenize_fn, remove_columns=train_dataset.column_names)
tokenized_train.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
train_loader = torch.utils.data.DataLoader(tokenized_train, batch_size=BATCH_SIZE, shuffle=True)

# =======================================================
# 3. Full-Parameter Model Loading & Optimizer
# =======================================================
model = AutoModelForCausalLM.from_pretrained(
    MODEL_DIR, 
    torch_dtype=torch.bfloat16, 
    trust_remote_code=True,
    device_map=None 
)
model.resize_token_embeddings(len(tokenizer))
model.gradient_checkpointing_enable()

# Utilize 8-bit AdamW to reduce VRAM consumption
optimizer = bnb.optim.PagedAdamW8bit(model.parameters(), lr=LEARNING_RATE)

num_training_steps = (len(train_loader) * 3) // GRAD_ACCUM
lr_scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.05 * num_training_steps), # Shortened warmup phase
    num_training_steps=num_training_steps
)

model, optimizer, train_loader, lr_scheduler = accelerator.prepare(
    model, optimizer, train_loader, lr_scheduler
)

# =======================================================
# 4. Training Loop
# =======================================================
model.train()
cite_id = tokenizer.convert_tokens_to_ids(CITE_TOKEN)

for epoch in range(3):
    inner_pbar = tqdm(train_loader, disable=not accelerator.is_local_main_process, desc=f"FFT Epoch {epoch}")
    
    for step, batch in enumerate(inner_pbar):
        with accelerator.accumulate(model):
            outputs = model(**batch)
            logits = outputs.logits
            labels = batch["labels"]

            # Shift sequence for Causal LM target matching
            shift_logits = logits[..., :-1, :].contiguous()
            shift_labels = labels[..., 1:].contiguous()
            
            loss_fct = nn.CrossEntropyLoss(reduction='none')
            loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
            
            # Substantially amplify the weight of the citation marker
            weights = torch.ones_like(shift_labels, dtype=torch.float)
            weights[shift_labels == cite_id] = 20.0
            
            # Compute loss strictly on unmasked tokens
            valid_mask = (shift_labels != -100).view(-1)
            weighted_loss = (loss * weights.view(-1) * valid_mask).sum() / (valid_mask.sum() + 1e-8)

            accelerator.backward(weighted_loss)
            
            if accelerator.sync_gradients:
                accelerator.clip_grad_norm_(model.parameters(), 1.0)
            
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()
            
            if accelerator.is_local_main_process:
                inner_pbar.set_postfix(
                    loss=f"{weighted_loss.item():.4f}", 
                    lr=f"{lr_scheduler.get_last_lr()[0]:.2e}"
                )

    # Save model artifacts at the conclusion of each epoch
    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        save_path = os.path.join(OUTPUT_DIR, f"epoch_{epoch}")
        unwrapped_model = accelerator.unwrap_model(model)
        unwrapped_model.save_pretrained(save_path)
        tokenizer.save_pretrained(save_path)
        print(f"[*] Model saved to {save_path}")