import re
import json
from openai import OpenAI

class CiteModelWorkers:
    def __init__(self, port, model_name):
        print(f"[*] Connecting to local vLLM API service (Port: {port}, Model: {model_name})...")
        # Minimalist connection pointing directly to the local vLLM server
        self.client = OpenAI(api_key="EMPTY", base_url=f"http://localhost:{port}/v1")
        self.model_name = model_name

    def _generate(self, prompt, max_tokens=1024, do_sample=False, temperature=0.1):
        """High-speed text generation function using the vLLM API."""
        # Call the completions API using the manually formatted prompt with special tokens
        response = self.client.completions.create(
            model=self.model_name,
            prompt=prompt,
            max_tokens=max_tokens,
            temperature=temperature if do_sample else 0.0,
            extra_body={
                "repetition_penalty": 1.1,
                "skip_special_tokens": False
            }
        )
        
        res = response.choices[0].text
        # Remove model-specific termination tokens
        return res.replace("<|im_end|>", "").replace("<|endoftext|>", "").strip()

    def locate_citations(self, text):
        """CiteLocator: Identifies exact locations in the text requiring citations."""
        prompt_text = "Perform a granular analysis of the logical flow to distinguish between original interpretations and claims that necessitate evidentiary support from the literature. For every instance where a sentence introduces a fact, benchmark, or theory not generated by the current study, place the [#CITE#] symbol at the exact junction where a citation is required"
        full_prompt = f"<|im_start|>system\n{prompt_text}<|im_end|>\n<|im_start|>user\n{text}<|im_end|>\n<|im_start|>assistant\n"
        
        pred = self._generate(full_prompt, max_tokens=1024)
        return pred.strip()

    def analyze_intents(self, marked_text):
        """QueryPlanner: Analyzes citation intents and extracts search keywords based on markers."""
        full_prompt_header = (
            "You are an expert academic citation analyst.\n\n"
            "### Task\n"
            "Analyze the context of the given text. For each citation marker [#CITE#], infer what keywords should be used to search for the paper that needs to be cited. Each [#CITE#] marker in the input must correspond to one [Index n] in the output in order, and the total number of indices must exactly match the number of citation markers.\n\n"
            "### Output Components\n"
            "1. <reasoning>: A 1-2 sentence logical analysis of the context explaining the core role of the citation.\n"
            "   MUST start with the fixed phrase: \"The purpose of this citation is to...\"\n"
            "2. <keywords>: 3-5 precise keywords to retrieve the target document.\n"
            "   - STRICTLY PROHIBITED: Do NOT include any author names or surnames.\n"
            "   - Focus on: contextually relevant keywords, specific research methods, exclusive technical terminology, problem formulation, model or dataset names, etc.\n\n"
            "### Constraints\n"
            "- Sequential Indexing: Start with [Index 0] and increment by 1 for each marker. Do NOT skip any numbers.\n"
            "- Strict Mapping: The total number of [Index n] blocks must exactly match the count of [#CITE#] markers in the input.\n"
            "- Multi-Ref Handling: If one [#CITE#] represents multiple references, provide multiple consecutive <reasoning> and <keywords> pairs under that single [Index n].\n"
            "- Output ONLY the structured content. Strictly NO conversational filler.\n\n"
            "### Output Format\n"
            "[Index X]\n"
            "<reasoning>...</reasoning>\n"
            "<keywords>[\"keyword 1\", \"keyword 2\", ...]</keywords>"
        )
        
        full_prompt = f"<|im_start|>system\n{full_prompt_header}<|im_end|>\n<|im_start|>user\n{marked_text}<|im_end|>\n<|im_start|>assistant\n"
        pred = self._generate(full_prompt, max_tokens=4096, do_sample=True, temperature=0.1)
        
        results = []
        try:
            blocks = re.split(r'\[Index (\d+)\]', pred)
            for i in range(1, len(blocks), 2):
                idx = int(blocks[i])
                content = blocks[i+1]
                
                reasoning_match = re.search(r'<reasoning>(.*?)</reasoning>', content, re.S | re.I)
                intent = reasoning_match.group(1).strip() if reasoning_match else "General background"
                
                keywords = []
                keywords_match = re.search(r'<keywords>(.*?)</keywords>', content, re.S | re.I)
                if keywords_match:
                    kw_str = keywords_match.group(1).strip()
                    try:
                        keywords = json.loads(kw_str)
                    except json.JSONDecodeError:
                        # Fallback parsing if LLM output is not perfect JSON
                        kw_str = kw_str.replace('[', '').replace(']', '').replace('"', '').replace("'", "")
                        keywords = [k.strip() for k in kw_str.split(',') if k.strip()]
                
                results.append({
                    "index": idx,
                    "intent": intent,
                    "keywords": keywords
                })
        except Exception as e:
            print(f"[Error] GRPO format parsing failed: {e}\nRaw output:\n{pred}")
            
        return results if results else [{"index": 0, "intent": "General background", "keywords": ["machine learning"]}]